// Generated by CoffeeScript 1.3.3
var Controller;

Controller = (function() {

  function Controller() {
    this.routes = [
      {
        path: "/",
        http_method: "get",
        method: "index"
      }, {
        path: "/index",
        http_method: "get",
        method: "index"
      }, {
        path: "/stats",
        http_method: "get",
        method: "stats"
      }, {
        path: "/comment/:id",
        http_method: "get",
        method: "comment"
      }, {
        path: "/shopchartview/:id",
        http_method: "get",
        method: "api_shopchartview"
      }, {
        path: "/contact",
        http_method: "get",
        method: "contact"
      }, {
        path: "/shops",
        http_method: "get",
        method: "api_shops"
      }, {
        path: "/shopviewtmpl/:id",
        http_method: "get",
        method: "api_shopviewtmpl"
      }, {
        path: "/welcome",
        http_method: "get",
        method: "api_welcome"
      }, {
        path: "/password",
        http_method: "get",
        method: "api_password"
      }, {
        path: "/shopcomment/:id",
        http_method: "get",
        method: "api_shopcomment"
      }, {
        path: "/shop/:id",
        http_method: "get",
        method: "api_shop"
      }
    ];
  }

  Controller.prototype.index = function(req, res) {
    var data;
    data = {
      title: 'Easy Sou',
      shops: [
        {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop1'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop2'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop3'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop4'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop5'
        }
      ]
    };
    return res.render('index', data);
  };

  Controller.prototype.stats = function(req, res) {};

  Controller.prototype.comment = function(req, res) {
    return res.json({
      comments: ['comment1', 'comment2', 'comment3', 'comment4', 'comment5', 'comment6', 'comment7']
    });
  };

  Controller.prototype.api_shopchartview = function(req, res) {
    return res.render('shopchartview', {
      title: 'Shop Chart View',
      id: req.params.id
    });
  };

  Controller.prototype.contact = function(req, res) {
    return res.render('contact', {
      title: 'Contact information'
    });
  };

  Controller.prototype.api_shop = function(req, res) {
    return res.json({
      commentGood: [10, 120, 230, 340, 350, 360],
      commentBad: [115, 25, 135, 245, 255, 365]
    });
  };

  Controller.prototype.api_shops = function(req, res) {
    var data;
    data = {
      title: 'Easy Sou',
      shops: [
        {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop5'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop6'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop7'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop8'
        }
      ]
    };
    return res.render('shops', data);
  };

  Controller.prototype.api_welcome = function(req, res) {
    return res.render('welcome', {
      title: 'Welcome(Login)'
    });
  };

  Controller.prototype.api_password = function(req, res) {
    return res.render('password', {
      title: 'Reset Password'
    });
  };

  Controller.prototype.api_shopcomment = function(req, res) {
    return res.render('shopcomment', {
      title: 'Reset Password',
      id: req.params.id
    });
  };

  Controller.prototype.api_shopviewtmpl = function(req, res) {
    var data;
    data = {
      title: 'Easy Sou',
      shops: [
        {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop' + (req.params.id + 1)
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop' + (req.params.id + 2)
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop' + (req.params.id + 3)
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop' + (req.params.id + 4)
        }
      ]
    };
    return res.render('shopviewtmpl', data);
  };

  return Controller;

})();

module.exports = Controller;
