// Generated by CoffeeScript 1.3.3
var Controller;

Controller = (function() {

  function Controller() {
    this.routes = [
      {
        path: "/",
        http_method: "get",
        method: "index"
      }, {
        path: "/index",
        http_method: "get",
        method: "index"
      }, {
        path: "/stats",
        http_method: "get",
        method: "stats"
      }, {
        path: "/comment/:id",
        http_method: "get",
        method: "comment"
      }, {
        path: "/contact",
        http_method: "get",
        method: "contact"
      }, {
        path: "/shops",
        http_method: "get",
        method: "api_shops"
      }, {
        path: "/shop/:id",
        http_method: "get",
        method: "api_shop"
      }
    ];
  }

  Controller.prototype.index = function(req, res) {
    var data;
    data = {
      title: 'Easy Sou',
      shops: [
        {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop1'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop2'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop3'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop4'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop5'
        }
      ]
    };
    return res.render('index', data);
  };

  Controller.prototype.stats = function(req, res) {};

  Controller.prototype.comment = function(req, res) {
    return res.json({
      comments: ['comment1', 'comment2', 'comment3', 'comment4', 'comment5', 'comment6', 'comment7']
    });
  };

  Controller.prototype.contact = function(req, res) {
    return res.render('contact', {
      title: 'Contact information'
    });
  };

  Controller.prototype.api_shop = function(req, res) {
    return res.json({
      commentGood: [10, 120, 230, 340, 350, 360],
      commentBad: [115, 25, 135, 245, 255, 365]
    });
  };

  Controller.prototype.api_shops = function(req, res) {
    return res.json({
      title: 'Easy Sou',
      shops: [
        {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop1'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop2'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop3'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop4'
        }, {
          shoplogo: 'wp-icon.png',
          shopwebsite: '#',
          shopname: 'EasySou',
          id: 'shop5'
        }
      ]
    });
  };

  return Controller;

})();

module.exports = Controller;
