// Generated by CoffeeScript 1.3.3
var Controller;

Controller = (function() {

  function Controller() {
    this.routes = [
      {
        path: "/",
        http_method: "get",
        method: "index"
      }, {
        path: "/index",
        http_method: "get",
        method: "index"
      }, {
        path: "/stats",
        http_method: "get",
        method: "stats"
      }, {
        path: "/comment",
        http_method: "post",
        method: "comment"
      }, {
        path: "/shops",
        http_method: "get",
        method: "get_shops"
      }
    ];
  }

  Controller.prototype.index = function(req, res) {
    return res.render('index.ejs');
  };

  Controller.prototype.get_shops = function(req, res) {};

  Controller.prototype.stats = function(req, res) {};

  Controller.prototype.comment = function(req, res) {};

  return Controller;

})();

module.exports = Controller;
