// Generated by CoffeeScript 1.3.3
var News_Schema;

News_Schema = (function() {

  function News_Schema() {
    var news;
    this.news_schema = new Schema({
      shopid: {
        type: String,
        "default": 'shopid'
      },
      news: {
        type: String,
        "default": 'abstract'
      },
      newsurl: {
        type: String,
        "default": 'full_url'
      },
      createtime: {
        type: Date,
        "default": Date.now
      }
    });
    news = "news_";
    return;
  }

  News_Schema.prototype.insert_news = function(news, category) {
    var news_doc, news_models;
    news_models = Mongoose.model("news", this.news_schema, news + category);
    news_doc = new news_models(news);
    return news_doc.save(function(err, doc) {
      if (err != null) {
        return logger.info("failed to insert_comment: " + err);
      }
    });
  };

  News_Schema.prototype.get_news_by_id = function(shopid, category, start, limit, callback) {
    var cur_model;
    cur_model = Mongoose.model("news", this.news_schema, news + category);
    return cur_model.find({
      shopid: shopid
    }).sort('-createtime').skip(start).limit(limit).select("news newsurl").exec(callback);
  };

  News_Schema.prototype.remove_news_by_time = function(time, category) {};

  News_Schema.prototype.remove_news_by_id = function(id, category) {};

  return News_Schema;

})();

module.exports = News_Schema;
