// Generated by CoffeeScript 1.3.3
/*
  put all the shops into one collection, which is called 'shops'
  e.g:
  @shop_model = Mongoose.model('shops',@shop_schema)
*/

var Mongoose, Schema, SchemaDesigner;

Mongoose = require("mongoose");

Schema = Mongoose.Schema;

Mongoose.connect("mongodb://127.0.0.1:27017/shops");

SchemaDesigner = (function() {

  function SchemaDesigner() {
    this.shop_schema = new Schema({
      shopname: {
        type: String,
        "default": 'fullname'
      },
      shopalias: [
        {
          type: String,
          "default": 'short name'
        }
      ],
      shopvisit: {
        type: Number,
        "default": 1000
      },
      shoppriority: {
        type: Number,
        "default": 1000
      },
      shopwebsite: {
        type: String,
        "default": 'fullurl'
      },
      shopphone: [
        {
          type: String,
          "default": '000000000'
        }
      ],
      shoponbusiness: {
        type: Boolean,
        "default": true
      },
      shopweekstats: {
        monday: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        tuesday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        wednesday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        thurday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        friday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        saturday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        sunday: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        weekday: [0, 0, 0, 0, 0],
        weekdaygood: [0, 0, 0, 0, 0],
        weekdaybad: [0, 0, 0, 0, 0]
      },
      shopdaystats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      shopmonthstats: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      shoplogo: {
        type: String,
        "default": './images/default.jpg'
      },
      shopgoodt: {
        type: Number,
        "default": 0
      },
      shopbadt: {
        type: Number,
        "default": 0
      },
      shopcover: [
        {
          type: String,
          "default": 'beijing'
        }
      ],
      shopaccount: {
        type: Number,
        "default": 0
      },
      shopcreatetime: {
        type: Date,
        "default": Date.now
      },
      shopcomments: [
        {
          body: String,
          date: Date
        }
      ],
      shopnews: [
        {
          type: String,
          "default": 'full name 1'
        }, {
          type: String,
          "default": 'full name 2'
        }, {
          type: String,
          "default": 'full name 3'
        }, {
          type: String,
          "default": 'full name 4'
        }, {
          type: String,
          "default": 'full name 5'
        }, {
          type: String,
          "default": 'full name 6'
        }, {
          type: String,
          "default": 'full name 7'
        }
      ]
    });
    this.shop_model = Mongoose.model('shops', this.shop_schema);
    this.conn = Mongoose.connection;
    this.conn.on('error', console.error.bind(console, 'connection error:'));
    this.conn.once('open', function() {
      return logger.info("success to open mongodb");
    });
    return;
  }

  SchemaDesigner.prototype.insert_shop = function(shop) {
    var shop_doc;
    logger.info("begin to insert_shop");
    shop_doc = new this.shop_model(shop);
    return shop_doc.save(function(err, doc) {
      if (err != null) {
        logger.info("insert_shop: " + err);
      }
      return logger.info("insert_shop: " + doc);
    });
  };

  SchemaDesigner.prototype.find = function(condition, fields, callback) {
    var _this = this;
    if (!(callback != null)) {
      return this.shop_model.find(condition, fields, function(err, docs) {
        if (err != null) {
          logger.info("find: " + err);
        }
        return _this.cachedata = docs;
      });
    } else {
      return this.shop_model.find(condition, fields, callback);
    }
  };

  return SchemaDesigner;

})();

module.exports = SchemaDesigner;
